name: Translate README

on:
  push:
    branches:
      - master
    paths:
      - 'README_de.md'
      - 'index.php'
      - 'config/config-sample.php'
      - 'privacy.php'

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Prepare Git user data
      run: |
        git config --global user.email "dbt@novatux.de"
        git config --global user.name "Thilo Graf"

    - name: Install tagit dependencies
      run: |
        pip install GitPython
        curl -o tagit.py https://raw.githubusercontent.com/dbt1/tagit/master/tagit.py
        chmod +x tagit.py

    - name: Verify tagit.py download
      run: |
        if [ ! -f tagit.py ]; then
         echo "tagit.py was not downloaded!"
         exit 1
        fi

    - name: Tagging
      run: |
        python tagit.py -f index.php -f README_de.md -f README_en.md --scheme-file ./.github/tagit-config.json
        rm tagit.py
